### ISSUE TITLE
There seems to be an OOM situation when computing the gossipcop data set

### ISSUE THREAD

**Issue by MH-limarco** [jiayingwu19/DECOR#1]
I tried to run with -Run DECOR using RTX-4090 and got "RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`" when using gossipcop profile.

I'm pretty sure it's an OOM situation because I'm using another profile. able to operate and
Similar results were obtained in the paper. So, is there any way to improve the above situation?

> Traceback (most recent call last):
>   File "src/gcn_decor.py", line 130, in <module>
>     acc, prec, recall, f1 = train(data, iter)
>   File "src/gcn_decor.py", line 100, in train
>     loss.backward()
>   File "N:\environment\Anaconda3\envs\py38_torch20_Gnn\lib\site-packages\torch\_tensor.py", line 487, in backward
>     torch.autograd.backward(
>   File "N:\environment\Anaconda3\envs\py38_torch20_Gnn\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
>     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### Environment
- Python                       3.8.10
- pytorch                      2.0.0
- pyg                            2.3.0 
- torch-cluster             1.6.1+pt20cu118
- torch-scatter             2.1.1+pt20cu118
- torch-sparse             0.6.17+pt20cu118
- torch-spline-conv     1.2.2+pt20cu118
- torchaudio                2.0.0 
- torchvision                0.15.0

**Comment by jiayingwu19** [comment]
Given the large scale of the GossipCop social graph (containing ~16.6k news article nodes), all experiments on the GossipCop dataset were conducted in a multi-GPU manner using RTX 3090 GPUs.

Please refer to the multi-GPU instructions in the commented lines of our source code. There, we provide an example of training on 4 GPUs. Specifically, uncomment the lines that begin with a single # mark. Set ``os.environ["CUDA_VISIBLE_DEVICES"] = "0, 1, 2, 3"``, and modify the definition of ``adj_transform`` in the ``GNNDecor`` class to ``self.adj_transform = torch.nn.DataParallel(MLP([3, mlp_width, 2]), device_ids=[0, 1, 2, 3])``.

Start multi-GPU training with the following command:
```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 python src/[base_gnn]_decor.py --dataset_name [dataset_name] 
```

Thanks for your message. We are glad that you found our work useful for your research.
